name: music_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  dots_indicator: ^2.1.2
  carousel_slider: ^4.2.1
  palette_generator: ^0.3.3
  lottie: ^1.4.3
  percent_indicator: ^4.2.3
  rxdart: ^0.27.7
  dio: ^4.0.6
  youtube_explode_dart: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  queue: ^3.1.0+1
  path_provider: ^2.1.3
  fluttertoast: ^8.2.6
  audio_video_progress_bar: ^2.0.3
  audio_session: ^0.1.21
  just_audio: ^0.9.39
  audio_service: ^0.18.15
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  internet_connection_checker: ^0.0.1+4
  tuple: ^2.0.2
  multiple_result: ^1.0.4
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  file_picker: ^5.5.0
  mp3_info: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation.json
