name: Build an unsigned apk

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build release apk
        run: flutter build apk --split-per-abi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Android apks
          path: build/app/outputs/flutter-apk/*release.apk
